### ISSUE TITLE
Warning: sizeof(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by sokolnikov911** [yii-dream-team/yii2-upload-behavior#29]
This PHP 7.2 error from required package `masterexploder/phpthumb`.
Actually on package page exist related issue: https://github.com/masterexploder/PHPThumb/issues/131, and someone made a PR: https://github.com/masterexploder/PHPThumb/pull/133
But because of this package is abadoned, I think need to find another way to fix it. Maybe to make own fork of this package.

**Comment by metalagman** [comment]
I thought about replacing the phpthumb with imagine library.

**Comment by dkrylovdotcom** [comment]
Hi! Author, please fix this issue.

composer update not help. It does not update masterexploder package

**Comment by Aleksey203** [comment]
i fixed here https://packagist.org/packages/aleksey203/yii2-upload-behavior

**Comment by dkrylovdotcom** [comment]
ok)
пн, июнь 24, 2019 в 13:41, Aleksey203  написал: 

	i fixed here https://packagist.org/packages/aleksey203/yii2-upload-behavior (https://packagist.org/packages/aleksey203/yii2-upload-behavior)

**Comment by dkrylovdotcom** [comment]
thx)
пн, июнь 24, 2019 в 13:41, Aleksey203  написал: 

	i fixed here https://packagist.org/packages/aleksey203/yii2-upload-behavior (https://packagist.org/packages/aleksey203/yii2-upload-behavior)

**Comment by klev-o** [comment]
Hi! Please fix this issue.
Still, the problem is relevant for php 7.2
Easy way: instead
`/**
     * The options for this class
     *
     * This array contains various options that determine the behavior in
     * various functions throughout the class.  Functions note which specific
     * option key / values are used in their documentation
     *
     * @var array
     */
    protected $options;`
add:
`protected $options = array();`

**Comment by Matvik** [comment]
Same issue. Can you fix this?

**Comment by g-rodigy** [comment]
Add in your composer 
````"repositories": [ { "type": "vcs", "url": "https://github.com/monter08/PHPThumb" }]````
 or own fork
Original repo has fix for 7.2 but still not release new version
